-- MySQL Script generated by MySQL Workbench
-- Thu Feb 23 16:55:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookingdb` DEFAULT CHARACTER SET utf8 ;
USE `bookingdb` ;


-- -----------------------------------------------------
-- Table `bookingdb`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookingdb`.`locations` ;

CREATE TABLE IF NOT EXISTS `bookingdb`.`locations` (
  `location_id` DOUBLE NOT NULL,
  `address` VARCHAR(30) NOT NULL,
  `information` LONGTEXT NULL DEFAULT NULL,
  `open_hour` INT NOT NULL,
  `close_hour` INT NOT NULL,
  PRIMARY KEY (`location_id`));


-- -----------------------------------------------------
-- Table `bookingdb`.`barbers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookingdb`.`barbers` ;

CREATE TABLE IF NOT EXISTS `bookingdb`.`barbers` (
  `barber_id` DOUBLE NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `locations_location_id` DOUBLE NOT NULL,
  `availabilities` LONGTEXT NULL DEFAULT NULL,
  `image_url` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`barber_id`),
  INDEX `barbers_locations_fk` (`locations_location_id` ASC) VISIBLE,
  CONSTRAINT `barbers_locations_fk`
    FOREIGN KEY (`locations_location_id`)
    REFERENCES `bookingdb`.`locations` (`location_id`));


-- -----------------------------------------------------
-- Table `bookingdb`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookingdb`.`customers` ;

CREATE TABLE IF NOT EXISTS `bookingdb`.`customers` (
  `client_id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(20) NULL DEFAULT NULL,
  `bookinghistory` LONGTEXT NULL DEFAULT NULL,
  `password` VARCHAR(80) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `bookingdb`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookingdb`.`services` ;

CREATE TABLE IF NOT EXISTS `bookingdb`.`services` (
  `service_id` DOUBLE NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`service_id`));


-- -----------------------------------------------------
-- Table `bookingdb`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookingdb`.`bookings` ;

CREATE TABLE IF NOT EXISTS `bookingdb`.`bookings` (
  `barbers_barber_id` DOUBLE NOT NULL,
  `booking_id` DOUBLE NOT NULL,
  `locations_location_id` DOUBLE NOT NULL,
  `datetime` DATETIME(6) NOT NULL,
  `customers_client_id` DOUBLE NOT NULL,
  `services_chosen` DOUBLE NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `bookings_barbers_fk` (`barbers_barber_id` ASC) VISIBLE,
  INDEX `bookings_customers_fk` (`customers_client_id` ASC) VISIBLE,
  INDEX `bookings_locations_fk` (`locations_location_id` ASC) VISIBLE,
  CONSTRAINT `bookings_barbers_fk`
    FOREIGN KEY (`barbers_barber_id`)
    REFERENCES `bookingdb`.`barbers` (`barber_id`),
  CONSTRAINT `bookings_customers_fk`
    FOREIGN KEY (`customers_client_id`)
    REFERENCES `bookingdb`.`customers` (`client_id`),
  CONSTRAINT `bookings_locations_fk`
    FOREIGN KEY (`locations_location_id`)
    REFERENCES `bookingdb`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

